<a href="https://colab.research.google.com/github/nagapandi1982/Colab-projects/blob/main/NN_Attrition_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2. can you predict the employee attrition in an organization based on the following features. The features and the dataset are given below. use a classification model with KNN algorithm
#Features:
#Age: Age of the employee (numerical).
#JobRole: The job role/position of the employee (categorical).
#MonthlyIncome: Employee's monthly salary (numerical).
#JobSatisfaction: A rating from 1 to 4 indicating the employee's satisfaction with the job (numerical).
#YearsAtCompany: Number of years the employee has been at the company (numerical).
#Attrition: Target label indicating whether the employee left the company (1 for attrition, 0 for noattrition)

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
# Sample data for training (Age,JobRole,MonthlyIncome,JobSatisfaction,YearsAtCompany,Attrition: 1=attrition, 0=No-attrition)
data = { 'Age': [29, 35, 40, 28, 45, 25, 50, 30, 37, 26],'MonthlyIncome': [4800, 6000, 3400, 4300, 11000, 3500, 12000, 5000, 3100, 4500],'JobSatisfaction': [3, 4, 2, 3, 4, 1, 4, 2, 2, 3],'YearsAtCompany': [4, 8, 6, 3, 15, 2, 20, 5, 9, 2],'Attrition': [1, 0, 0, 1, 0, 1, 0, 0, 0, 1] }
# Convert data to DataFrame
# data = pd.read_csv("/content/sample_data/bankloan_classification_train.csv")

In [6]:
data = pd.DataFrame(data)
# Split features and labels
# Separate features (X) and labels (y)
X = data.iloc[:, :-1].values  # All columns except the last one are features
y = data.iloc[:, -1].values   # The last column is the target (Outcome: 0 or 1)

In [8]:
print (X)
print (y)

[[   29  4800     3     4]
 [   35  6000     4     8]
 [   40  3400     2     6]
 [   28  4300     3     3]
 [   45 11000     4    15]
 [   25  3500     1     2]
 [   50 12000     4    20]
 [   30  5000     2     5]
 [   37  3100     2     9]
 [   26  4500     3     2]]
[1 0 0 1 0 1 0 0 0 1]


In [11]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data (normalize the age and loan_amount)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the neural network model
model = Sequential()
# Corrected input_dim to match the number of features in X_train_scaled (which is 4)
model.add(Dense(16, input_dim=X_train_scaled.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))  # Hidden layer
model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=100, batch_size=4, verbose=0)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

# Predict for 3 new samples
# New customer samples (Age, MonthlyIncome, JobSatisfaction, YearsAtCompany)
# The new_customers array must also have 4 features to match the model's input
new_customers = np.array([[28, 6000, 3, 5], [50, 17000, 4, 10], [38, 11000, 2, 8]])

# Scale the new customer data
new_customers_scaled = scaler.transform(new_customers)

# Predict whether they will repay or default
predictions = model.predict(new_customers_scaled)

# Print predictions (1 = repay, 0 = default)
for i, prediction in enumerate(predictions):
    print(f"Customer {i + 1}: {'Attrition' if prediction >= 0.5 else 'Noattrition'}")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 1.0000 - loss: 0.5008
Test Accuracy: 100.00%
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Customer 1: Attrition
Customer 2: Noattrition
Customer 3: Noattrition
